#pragma once

#define IDR_CSV_WEAPONS 101
#define IDR_CSV_DLC_WEAPONS 102
#define IDR_CSV_ARMOR 103
#define IDR_CSV_DLC_ARMOR 104
#define IDR_CSV_TALISMANS 105
#define IDR_CSV_DLC_TALISMANS 106
#define IDR_CSV_GOODS 107
#define IDR_CSV_DLC_ITEMS 108
#define IDR_CSV_NPCS 109
#define IDR_CSV_DLC_NPCS 110
