#pragma once

#define IDR_JSON_WEAPONS 101
#define IDR_JSON_CUSTOM_WEAPONS 102
#define IDR_JSON_ARMOR 103
#define IDR_JSON_TALISMANS 104
#define IDR_JSON_GOODS 105
#define IDR_JSON_ASHES 106
#define IDR_JSON_NPCS 107
